version: '3'

services:
  frontend:
    build:
      context: ..
      dockerfile: "docker/Dockerfile"
    container_name: frontend-csc309-team
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - "TZ=America/Toronto"